# Git

## A quick overview:
https://github.com/llendway/github_for_collaboration/blob/master/github_for_collaboration.md

## Git step by step

If you don't have Git, install it:  
https://happygitwithr.com/install-git.html  

Make sure .gitignore contains the following files:  
.Renviron
.Rprofile

Introduce yourself to Git:  
In the shell (Terminal tab in RStudio):  
git config --global user.name 'Jane Doe'  
git config --global user.email 'jane@example.com'  
git config --global --list  

For more advanced tasks, use GitHub Desktop:  
https://desktop.github.com  

Store your GitHub PAT (Personal Access Token):  
https://happygitwithr.com/https-pat.html  

Use one of three ways to add your project to GitHub:  
Brand new project:  
https://happygitwithr.com/new-github-first.html  
Existing project without version control:  
https://happygitwithr.com/existing-github-first.html  
Existing project under local version control:  
https://happygitwithr.com/existing-github-last.html  

Troubleshooting if RStudio can't detect Git:  
https://happygitwithr.com/rstudio-see-git.html  

Git vocabulary:  
https://happygitwithr.com/git-basics.html  

Remote setups (try to stick to GitHub first discussed above):  
https://happygitwithr.com/common-remote-setups.html  

Useful Git workflows and dealing with conflicts:  
https://happygitwithr.com/workflows-intro.html  
https://happygitwithr.com/push-rejected.html  
https://happygitwithr.com/pull-tricky.html  

Additional resources:  
https://happygitwithr.com/ideas-for-content.html  

Suggested workflow:  
1) Initialize repository on GitHub.com under the UHERO account.  
2) Clone it via RStudio project setup.  
3) Commit changes, pull, resolve issues, push.
3*) If work in a branch (create in RStudio), commit to branch, (pull) push to remote, pull request on GitHub.com from branch to main, merge, delete branch on GitHub.com.

