project:
  type: book
  output-dir: _book
  # copy contents of _book into docs folder to show on github pages

book:
  title: "User guide to UHERO's forecast processes"
  reader-mode: true

  page-footer:
    left: |
      Author: Peter Fuleky
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>

  output-file: forecastr
  author: "Peter Fuleky"
  date: last-modified
  
  search: true
  repo-url: https://github.com/UHERO/forecastr_book/
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  sidebar:
    style: floating
  chapters:
    - index.qmd
    - project.qmd
    - git.qmd
    - renv.qmd
    - setup.qmd
    - fcutils.qmd
    # - utilfuns.qmd
    - bestpract.qmd
    - modselect.qmd
    # - simulation.qmd
    # - notes.qmd

comments:
  hypothesis: false

format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
    css: style.css
    number-depth: 2
    
    author-meta: "Peter Fuleky"
    callout-appearance: simple

  pdf:
    documentclass: scrreport
    keep-tex: true
    number-depth: 2

  epub:
    toc: true
    number-depth: 2

editor: source
